import os
WINDOW_WIDTH = 600
WINDOW_HEIGHT = 400
WINDOW_POSITION_RIGHT = 400
WINDOW_POSITION_DOWN = 200

COLOR_BLACK = '#726461'
COLOR_RED = '#ff3333'
COLOR_BLUE = '#53D4F7'
COLOR_GREEN = '#00b359'
COLOR_WHITE = '#ffffff'
COLOR_PURPLE = '#a64dff'
COLOR_YELLOW = '#ffff00'
COLOR_BG = '#F2E69C'

PATH_DIRECTORY = os.path.dirname(__file__)
PATH_IMAGES = os.path.join(PATH_DIRECTORY,'images')